config/routes.rb
Rails.application.routes.draw do
  resources :reservations

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def index
    @reservations = Reservation.all
  end

  def show
  end

  def new
    @reservation = Reservation.new
  end

  def edit
  end

  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
        format.js
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:city, :arrival_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookHotel</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/themes/le-frog/jquery-ui.css' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(@reservation, remote: true) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, id: "city" %>
  </div>
  <div class="field">
    <%= f.label :arrival_date %><br>
    <%= f.text_field :arrival_date, id: "date_in" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<tr>
  <td><%= reservation.city %></td>
  <td><%= reservation.arrival_date %></td>
  <td><%= link_to "Show", reservation %></td>
  <td><%= link_to "Edit", edit_reservation_path(reservation) %></td>
  <td><%= link_to "Cancel", reservation, method: :delete, 
    data: { confirm: "Are you sure?" } %></td>
</tr>

app/views/reservations/create.js.erb
$("#reservations_table tr:last").after("<%= j render @reservation %>");

// Clear the form
$("#form_container input[type=text]").val("");

// Refocus inside city textfield
$("#city").focus();

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Listing reservations</h1>

<table id="reservations_table">
  <thead>
    <tr>
      <th>City</th>
      <th>Arrival date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @reservations %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path, 
  remote: true, id: "new_reservation_link" %>
<div id="form_container" />

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/new.js.erb
$('#form_container').html('<%= j render template: "reservations/new.html.erb" %>');
$('#new_reservation_link').hide();

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @reservation.city %>
</p>

<p>
  <strong>Arrival date:</strong>
  <%= @reservation.arrival_date %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>